// HomePage — the landing screen. Ported from Frontend/index.html's hero and
// "how it works" explainer. Presentational only: no engine calls, no cohort
// state. The cursor-scrub hero video is the one piece of interaction, ported
// from shared.js's HERO DOG SCRUB block as a plain effect — no dependency.
//
// ─── REDESIGN PHASE 3 — ONE EXPLANATION, NOT THREE ─────────────────────────
//
// This page used to explain Kyndra three times on one scroll:
//
//   "What is Kyndra?"              two paragraphs of prose
//   "How does Kyndra work?"        five numbered steps
//   "Matching, without the black   three numbered steps — 01 Filter,
//    box."                         02 Derive, 03 Find a stable match
//
// The third list restated steps 02-04 of the second one in more technical
// language, which is the exact pattern the brief calls out (§7, "repeating
// the same explanation in multiple places"). A visitor read the same idea
// three times and was no clearer after the third.
//
// Now there is ONE progression (§10), in plain language, and the mechanics
// that used to be a whole third section sit behind a disclosure — brief §15's
// level 4, "a normal user should not be forced to understand Gale-Shapley; a
// technical judge should still be able to inspect it". Nothing was deleted:
// every claim the third section made is still on the page, one click down.

import { useEffect, useRef } from 'react';
import type { Page } from './NavBar';
import { JourneyTrack } from './JourneyTrack';
import { Disclosure } from './Disclosure';

/**
 * How many frames live in `public/hero-dog/`.
 *
 * Generated by `scripts/extract-hero-frames.mjs`, which prints a reminder to
 * update this if the count ever changes. Read that script before touching any
 * of these numbers — the frame RANGE was chosen by measuring the footage, and
 * the measurement is written down there.
 */
const FRAME_COUNT = 34;

/**
 * Native pixel size of every frame, and therefore of the canvas.
 *
 * The canvas backing store is deliberately the SOURCE resolution rather than
 * `box × devicePixelRatio`. On a 2x display the 370px box wants 740 device
 * pixels and the frames only have 512, so sizing to the display would spend
 * memory and fill rate rendering detail that does not exist. This is also
 * exactly what the <video> element it replaces did, so the hero looks the
 * same as before at every zoom level and viewport.
 */
const FRAME_WIDTH = 512;
const FRAME_HEIGHT = 910;

/**
 * The neutral, forward-facing pose — frame 73 of the source, index 16 here.
 *
 * Doubles as the rest position (where the head returns when the cursor
 * leaves) and as the still image behind the canvas.
 */
const NEUTRAL_FRAME = 16;

/**
 * Smoothing time constant, in milliseconds: the head covers ~63% of the
 * remaining distance in this long.
 *
 * Expressed as a time constant rather than as a per-frame fraction because a
 * per-frame fraction is silently twice as fast on a 120Hz display as on a
 * 60Hz one. The old code eased 0.16 of the gap per frame, which is this same
 * curve at ~95ms — on a 60Hz display only. 70ms is a little quicker, which
 * the removal of the decoder's latency leaves room for.
 */
const FOLLOW_TAU_MS = 70;

/** Below this gap (in progress, 0–1) the head has arrived; stop the loop. */
const SETTLE = 0.002;

/** A tab that was in the background hands back an enormous dt. Ignore it. */
const MAX_FRAME_MS = 64;

const framePath = (index: number) => `/hero-dog/frame-${String(index).padStart(2, '0')}.webp`;

const clamp01 = (n: number) => Math.min(1, Math.max(0, n));

/**
 * The cursor-tracking dog.
 *
 * ─── WHAT THIS REPLACED, AND WHY ───────────────────────────────────────────
 *
 * Cursor X used to be converted to a timestamp and written to
 * `video.currentTime` on a 4.3MB H.264 file. Its keyframes are 0.967s apart,
 * so an arbitrary timestamp is not an addressable frame: the decoder seeks to
 * the nearest keyframe and decodes forward, up to 28 frames of work for one
 * requested position. The previous pass had already stopped issuing a seek
 * while one was in flight, which removed the cancellation storm but not the
 * cost of the seeks themselves — the dog still arrived late, and lagged
 * hardest exactly when the cursor moved fastest.
 *
 * Now the 34 frames the interaction actually uses are fetched once, decoded
 * once into ImageBitmaps, and drawn with a single `drawImage` per animation
 * frame. Choosing a frame is an array index. There is no decoder in the loop
 * at all, so the cost of a cursor movement no longer depends on how far it
 * moved.
 *
 * ─── AND THE THING THAT WAS ACTUALLY WRONG ─────────────────────────────────
 *
 * The mapping pointed the wrong way. See scripts/extract-hero-frames.mjs:
 * the old 0–2.0s range ran the dog's head LEFT as the cursor moved right and
 * then did nothing at all across the right half of the hero. Frames 57–90 of
 * the source — index 0–33 here — sweep leftmost to rightmost, so index now
 * tracks cursor position directly and the whole width of the hero does
 * something.
 *
 * ─── SHAPE ─────────────────────────────────────────────────────────────────
 *
 *   pointermove  →  target (a number, 0–1)      no layout reads, no React
 *   rAF          →  current eases toward target
 *                →  index = round(current × 33)
 *                →  drawImage, but only when the index actually changed
 *                →  reschedule only while unsettled
 *
 * Nothing here touches React state: a re-render per pointer event would
 * rebuild the whole page for a head turn.
 */
function useHeroDogTracking(
  canvasRef: React.RefObject<HTMLCanvasElement | null>,
  heroRef: React.RefObject<HTMLElement | null>,
) {
  useEffect(() => {
    const canvas = canvasRef.current;
    const hero = heroRef.current;
    if (canvas === null || hero === null) return;

    const stage = hero.querySelector('.hero-dog');

    // The whole feature is a CURSOR interaction, so on a touch device it is
    // 618KB of frames that can never be used. The still image underneath the
    // canvas carries the hero on those devices, which is why this can simply
    // decline to load anything.
    //
    // Optional-called: matchMedia is absent in jsdom, and a missing
    // media-query API is not a reason to throw during render. No answer means
    // no cursor, so nothing is fetched — the safe default.
    if (window.matchMedia?.('(pointer: fine)').matches !== true) return;

    // Reduced motion keeps the picture and drops the chase. Unlike the video
    // version, which downloaded 4.3MB and then refused to animate it, this
    // does not fetch the frames at all: the still image is the calm state,
    // and it is already on screen.
    if (window.matchMedia?.('(prefers-reduced-motion: reduce)').matches === true) return;

    // Universal in browsers that matter, but a missing decoder must degrade
    // to the still image rather than throw.
    if (typeof createImageBitmap !== 'function') return;

    const context = canvas.getContext('2d', { alpha: false });
    if (context === null) return;

    canvas.width = FRAME_WIDTH;
    canvas.height = FRAME_HEIGHT;

    let frames: ImageBitmap[] = [];
    let ready = false;
    let onScreen = true;
    let requested = false;

    let target = NEUTRAL_FRAME / (FRAME_COUNT - 1);
    let current = target;
    let drawnIndex = -1;

    let loop: number | null = null;
    let lastFrameTime = 0;

    const aborter = new AbortController();

    // ─── The hero's box, read once instead of per event ────────────────────
    //
    // getBoundingClientRect() forces a layout flush, and the old code called
    // it inside the pointer handler — on every single move. Only `left` and
    // `width` are needed and neither changes while the cursor moves, so it is
    // cached and invalidated when the box can actually have moved. Vertical
    // scrolling does not affect either; the page never scrolls horizontally.

    let box: { left: number; width: number } | null = null;

    const measure = () => {
      const rect = hero.getBoundingClientRect();
      box = { left: rect.left, width: rect.width };
    };

    const invalidate = () => {
      box = null;
    };

    // ─── Drawing ───────────────────────────────────────────────────────────

    const draw = () => {
      const index = Math.round(current * (FRAME_COUNT - 1));
      if (index === drawnIndex) return; // same frame — drawing it again is free work
      const bitmap = frames[index];
      if (bitmap === undefined) return;
      drawnIndex = index;
      context.drawImage(bitmap, 0, 0, FRAME_WIDTH, FRAME_HEIGHT);
    };

    const step = (now: number) => {
      loop = null;
      if (!ready) return;

      // Frame-rate independent exponential smoothing. dt is clamped because a
      // backgrounded tab hands back hundreds of milliseconds at once, and an
      // unclamped step would teleport the head on return.
      const dt = Math.min(now - lastFrameTime, MAX_FRAME_MS);
      lastFrameTime = now;

      const delta = target - current;
      const settled = Math.abs(delta) < SETTLE;
      current = settled ? target : current + delta * (1 - Math.exp(-dt / FOLLOW_TAU_MS));

      draw();

      // Settled means the head is where the cursor asked and nothing is
      // moving. Stopping here is what keeps an idle hero at zero cost — no
      // rAF, no micro-jitter, no repaint.
      if (!settled) loop = requestAnimationFrame(step);
    };

    const kick = () => {
      if (loop !== null || !ready) return;
      lastFrameTime = performance.now();
      loop = requestAnimationFrame(step);
    };

    // ─── Loading ───────────────────────────────────────────────────────────

    const load = async () => {
      if (requested) return;
      requested = true;
      try {
        const decoded = await Promise.all(
          Array.from({ length: FRAME_COUNT }, async (_unused, index) => {
            const response = await fetch(framePath(index), { signal: aborter.signal });
            if (!response.ok) throw new Error(`hero frame ${index}: ${response.status}`);
            return createImageBitmap(await response.blob());
          }),
        );

        if (aborter.signal.aborted) {
          for (const bitmap of decoded) bitmap.close();
          return;
        }

        frames = decoded;
        ready = true;
        // Paint the rest pose immediately so the canvas is never a blank
        // rectangle over the still image it is about to replace.
        draw();
        stage?.setAttribute('data-scrub', 'ready');
        // The cursor may already have moved over the hero while this was
        // loading; target is up to date, so honour it rather than waiting for
        // the next movement.
        kick();
      } catch (error) {
        if (aborter.signal.aborted) return;
        // The still image stays. 'failed' keeps the hint hidden, so nothing
        // ever invites a visitor to interact with a dog that cannot respond.
        stage?.setAttribute('data-scrub', 'failed');
        if (import.meta.env.DEV) console.warn('hero dog frames failed to load', error);
      }
    };

    // Off the critical path: the hero reads and renders without this, and the
    // still image is already showing the dog.
    const whenIdle = () => {
      // Not `'requestIdleCallback' in window` — that narrows `window` itself
      // to never in the else branch. Safari still lacks it.
      if (typeof window.requestIdleCallback === 'function') {
        window.requestIdleCallback(() => void load(), { timeout: 2000 });
      } else {
        window.setTimeout(() => void load(), 1200);
      }
    };
    if (document.readyState === 'complete') whenIdle();
    else window.addEventListener('load', whenIdle, { once: true });

    // ─── Input ─────────────────────────────────────────────────────────────
    //
    // The handler does three cheap things: read a cached box, write a number,
    // and make sure the loop is running. Everything expensive happens in the
    // loop, at most once per displayed frame.

    const onPointerMove = (event: PointerEvent) => {
      if (!onScreen) return;
      if (box === null) measure();
      if (box === null || box.width <= 0) return;

      target = clamp01((event.clientX - box.left) / box.width);

      // Only 'active' — never 'ready'. `ready` is set when the frames decode
      // and by nothing else, because it is what makes the hint visible.
      // Setting it here would put "Move your cursor" back over a dog that
      // cannot yet respond.
      if (ready) {
        stage?.setAttribute('data-scrub', 'active');
        kick();
      }
    };

    // Deliberate exit behaviour: the head returns to the forward pose rather
    // than staying frozen wherever the cursor happened to leave.
    const onPointerLeave = () => {
      target = NEUTRAL_FRAME / (FRAME_COUNT - 1);
      kick();
    };

    hero.addEventListener('pointermove', onPointerMove, { passive: true });
    hero.addEventListener('pointerleave', onPointerLeave, { passive: true });
    window.addEventListener('resize', invalidate, { passive: true });

    // ─── Visibility ────────────────────────────────────────────────────────
    //
    // Absent in jsdom, and a missing observer is not a reason to throw during
    // render — the same trap matchMedia set above. Without it the pointer
    // handler simply runs whenever the cursor is over the hero, which is
    // already correct; the observer is an optimisation, not the mechanism.

    let viewport: IntersectionObserver | null = null;
    if (typeof IntersectionObserver === 'function') {
      viewport = new IntersectionObserver(
        (entries) => {
          const entry = entries[0];
          if (entry === undefined) return;
          onScreen = entry.isIntersecting;
          if (!onScreen && loop !== null) {
            cancelAnimationFrame(loop);
            loop = null;
          }
        },
        { threshold: 0 },
      );
      viewport.observe(hero);
    }

    // The hero's box moves when the layout reflows around it, which a window
    // resize does not always cover (a scrollbar appearing, for one).
    let resizes: ResizeObserver | null = null;
    if (typeof ResizeObserver === 'function') {
      resizes = new ResizeObserver(invalidate);
      resizes.observe(hero);
    }

    return () => {
      aborter.abort();
      hero.removeEventListener('pointermove', onPointerMove);
      hero.removeEventListener('pointerleave', onPointerLeave);
      window.removeEventListener('resize', invalidate);
      window.removeEventListener('load', whenIdle);
      viewport?.disconnect();
      resizes?.disconnect();
      if (loop !== null) cancelAnimationFrame(loop);
      // ImageBitmaps hold decoded pixel buffers outside the JS heap; the GC
      // will not reclaim them promptly on its own.
      for (const bitmap of frames) bitmap.close();
      frames = [];
    };
  }, [canvasRef, heroRef]);
}

/**
 * The five steps, in the visitor's language rather than the pipeline's.
 *
 * These map onto the engine's real stages (Architecture §6: FILTER → DERIVE →
 * MATCH → VERIFY → EXPLAIN) — the wording changed, the process did not. The
 * engine's own names for them are in the disclosure below.
 */
const STEPS: { label: string; detail: string }[] = [
  { label: 'Tell us about the household', detail: 'Home, routine, experience, and what they want.' },
  { label: 'Check what each animal needs', detail: 'Every animal arrives with its own requirements.' },
  { label: 'Rule out what cannot work', detail: 'Unsafe or unsuitable pairings are removed, not ranked.' },
  { label: 'Match both sides at once', detail: 'The whole group is settled together, not first-come.' },
  { label: 'Explain every result', detail: 'Each proposal carries the reasons behind it.' },
];

export function HomePage({ onNavigate }: { onNavigate: (page: Page) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  // The hero SECTION is the tracking region, not the viewport and not the
  // dog's own box — see the note on useHeroDogTracking.
  const heroRef = useRef<HTMLElement>(null);
  useHeroDogTracking(canvasRef, heroRef);

  return (
    <>
      <header className="hero" ref={heroRef}>
        <div className="hero-inner">
          <div className="hero-copy-block">
            <span className="eyebrow">For animal shelters</span>
            <h1>
              Where the right homes meet the <em>right animals.</em>
            </h1>
            <p className="hero-copy">
              Kyndra weighs what every animal needs against what every household can offer,
              rules out the pairings that would not work, and proposes who should go with
              whom — with the reasons attached.
            </p>
            <div className="hero-actions">
              <button type="button" className="primary" onClick={() => onNavigate('cohort')}>
                Start with the demo cohort
              </button>
              <button type="button" className="secondary" onClick={() => onNavigate('match')}>
                Build your own
              </button>
            </div>
            <p className="hero-note">Kyndra proposes. Shelter staff decide.</p>
          </div>

          {/* Two layers, and the bottom one is never empty.
              ==============================================================
              The still is the dog's neutral pose, and it is the ONLY thing
              that loads on a touch device, under reduced motion, or if the
              frames fail. That is a change of kind, not degree: the <video>
              this replaced shipped preload="none", so every one of those
              cases previously got a flat warm rectangle where the dog should
              be — the hero's whole image, absent, on every phone.

              The canvas sits on top and fades in once the frames are
              decoded. It carries the animation and nothing else, so it is
              aria-hidden; the still holds the real alt text.

              The wrapper used to carry an aria-label. On a plain <div> with
              no role that is ignored by most assistive tech, so the hero's
              only description was one screen readers were free to drop. It
              is now on the <img>, where it is an alt text and always
              announced. */}
          <div className="hero-dog">
            <img
              className="hero-dog__still"
              src={framePath(NEUTRAL_FRAME)}
              alt="A beagle sitting, facing forward."
              width={FRAME_WIDTH}
              height={FRAME_HEIGHT}
              decoding="async"
              draggable={false}
            />
            <canvas ref={canvasRef} className="hero-dog__canvas" aria-hidden="true" />
            <div className="hero-dog-label">Move your cursor</div>
          </div>
        </div>
      </header>

      <main className="page">
        <section id="what">
          <JourneyTrack step={1} />
          <div className="section-head section-head--tight">
            <div>
              <h2>What is Kyndra?</h2>
            </div>
          </div>
          <p className="onboarding-copy">
            Matching animals to homes by hand means one coordinator holding every animal&rsquo;s
            needs and every household&rsquo;s limits in their head at once — for every possible
            pairing. It does not scale, and under time pressure it is easy to miss a conflict,
            or a good fit. Kyndra does that comparison in full, every time, and shows its work.
          </p>
        </section>

        {/* Full-bleed tint band — the one visual break on the page, and the
            one thing on it a visitor has to understand. */}
        <section id="process" className="section-band">
          <div className="section-head section-head--tight">
            <div>
              <h2>How it works</h2>
              <p>Five steps, run the same way every time.</p>
            </div>
          </div>
          <ol className="process-flow">
            {STEPS.map((step, index) => (
              <li key={step.label} className="process-flow__step">
                <span className="process-flow__num">{String(index + 1).padStart(2, '0')}</span>
                <strong>{step.label}</strong>
                <span>{step.detail}</span>
              </li>
            ))}
          </ol>

          <div className="hero-actions">
            <button type="button" className="primary" onClick={() => onNavigate('cohort')}>
              See it on a real cohort →
            </button>
          </div>

          {/* Level 4 (§15) — the mechanics, for whoever wants them. This was
              a full third section of the page until Phase 3; every claim it
              made is still here, one click down instead of in the scroll of
              someone who only wanted to know what the product does. */}
          <Disclosure
            title="How the matching actually works"
            teaser="The method, the guarantee it gives, and why it is not a ranking."
          >
            <p className="onboarding-copy onboarding-copy--secondary">
              Kyndra is not an AI decision-maker. It proposes an assignment and explains it;
              staff decide. Requirements are treated as actual requirements — a pairing that
              fails one is removed outright, never just scored lower.
            </p>

            <div className="steps">
              <div className="step">
                <b>01</b>
                <div>
                  <strong>Rule out the impossible</strong>
                  <br />
                  <span>
                    Some matches are not safe or suitable — Kyndra checks every
                    animal–household pair against those requirements ("hard constraints")
                    first and removes the ones that fail, rather than just ranking them
                    lower.
                  </span>
                </div>
              </div>
              <div className="step">
                <b>02</b>
                <div>
                  <strong>Build both sides separately</strong>
                  <br />
                  <span>
                    What a household wants and what an animal needs are derived from
                    different information, and never from one shared score. Nobody
                    hand-ranks a list.
                  </span>
                </div>
              </div>
              <div className="step">
                <b>03</b>
                <div>
                  <strong>Settle the whole group at once</strong>
                  <br />
                  <span>
                    Gale–Shapley deferred acceptance produces a <i>stable</i> assignment:
                    no animal and household would both rather have each other than what
                    they were given.
                  </span>
                </div>
              </div>
            </div>

            <div className="reason">
              <b>Why this matters</b>
              A proposal with its reasons attached can be argued with. An opaque ranking
              cannot.
            </div>
          </Disclosure>
        </section>
      </main>
    </>
  );
}
